# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './frontend/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1200, 800))
        Form.setMaximumSize(QtCore.QSize(1200, 800))
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setStyleSheet("QLineEdit {\n"
"    background-color: #fff; \n"
"}\n"
"\n"
"QGraphicsView {\n"
"background-image: url(:/data/LOGO.png);\n"
"background-repeat: no-repeat;\n"
"width: 200px;\n"
"height: 50px;\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tb_main = QtWidgets.QTabWidget(Form)
        self.tb_main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_main.sizePolicy().hasHeightForWidth())
        self.tb_main.setSizePolicy(sizePolicy)
        self.tb_main.setMinimumSize(QtCore.QSize(1220, 805))
        self.tb_main.setMaximumSize(QtCore.QSize(1220, 805))
        self.tb_main.setSizeIncrement(QtCore.QSize(0, 0))
        self.tb_main.setBaseSize(QtCore.QSize(0, 0))
        self.tb_main.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tb_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tb_main.setAcceptDrops(False)
        self.tb_main.setToolTip("")
        self.tb_main.setAutoFillBackground(True)
        self.tb_main.setStyleSheet("QTabBar {\n"
"font-weight: 600;\n"
"font-size: 12px;\n"
"background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #2B4D9B;\n"
"    color: #fff;\n"
"    padding: 20px 10px 20px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    /*background: #000059;*/\n"
"background-color: #296EFA;\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"    border-right: none;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #1CE0B5;\n"
"    color: #000059;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTabBar::tab::last {\n"
"    border-bottom: none;\n"
"    border-color: #fff;\n"
"    background: #2B4D9B;\n"
"    color: #fff;\n"
"    padding: 300px 10px 20px 10px;\n"
"}\n"
"\n"
"QTabBar::tab::last::hover {\n"
"    background: #2B4D9B;\n"
"}\n"
"\n"
"\n"
"QTabWidget QStackedWidget > QWidget  \n"
"{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tb_main.setTabPosition(QtWidgets.QTabWidget.West)
        self.tb_main.setDocumentMode(True)
        self.tb_main.setTabsClosable(False)
        self.tb_main.setTabBarAutoHide(False)
        self.tb_main.setObjectName("tb_main")
        self.tb_visualisation = QtWidgets.QWidget()
        self.tb_visualisation.setStyleSheet("")
        self.tb_visualisation.setObjectName("tb_visualisation")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tb_visualisation)
        self.groupBox_18.setGeometry(QtCore.QRect(236, 0, 931, 81))
        self.groupBox_18.setStyleSheet("#groupBox_18 {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_18)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 869, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_21.setContentsMargins(0, 5, 5, 5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_20.setStyleSheet("#label_20 {\n"
"    font-size: 14px;    \n"
"    font-weight: 600;\n"
"    color: #fff;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.lb_stat_employee = QtWidgets.QLabel(self.layoutWidget)
        self.lb_stat_employee.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lb_stat_employee.setStyleSheet("#lb_stat_employee {\n"
"    font-size: 18px;    \n"
"    font-weight: 800;\n"
"    color: #fff;\n"
"}")
        self.lb_stat_employee.setObjectName("lb_stat_employee")
        self.horizontalLayout_21.addWidget(self.lb_stat_employee)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_21.setStyleSheet("#label_21 {\n"
"    font-size: 14px;    \n"
"    font-weight: 600;\n"
"    color: #fff;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.lb_stat_vehicle = QtWidgets.QLabel(self.layoutWidget)
        self.lb_stat_vehicle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lb_stat_vehicle.setStyleSheet("#lb_stat_vehicle {\n"
"    font-size: 18px;    \n"
"    font-weight: 800;\n"
"    color: #fff;\n"
"}")
        self.lb_stat_vehicle.setObjectName("lb_stat_vehicle")
        self.horizontalLayout_21.addWidget(self.lb_stat_vehicle)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_22.setStyleSheet("#label_22 {\n"
"    font-size: 14px;    \n"
"    font-weight: 600;\n"
"    color: #fff;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.lb_stat_warnings = QtWidgets.QLabel(self.layoutWidget)
        self.lb_stat_warnings.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lb_stat_warnings.setStyleSheet("#lb_stat_warnings {\n"
"    font-size: 18px;    \n"
"    font-weight: 800;\n"
"    color: #fff;\n"
"}")
        self.lb_stat_warnings.setObjectName("lb_stat_warnings")
        self.horizontalLayout_21.addWidget(self.lb_stat_warnings)
        spacerItem = QtWidgets.QSpacerItem(200, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.layoutWidget1 = QtWidgets.QWidget(self.tb_visualisation)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 120, 871, 644))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(850, 642))
        self.label.setMaximumSize(QtCore.QSize(850, 642))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #fff;\n"
"    border-radius: 8px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_20.addWidget(self.label)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tb_visualisation)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 0, 240, 810))
        self.groupBox_10.setMinimumSize(QtCore.QSize(240, 810))
        self.groupBox_10.setMaximumSize(QtCore.QSize(240, 810))
        self.groupBox_10.setStyleSheet("#groupBox_10 {\n"
"    background-color: #000059;\n"
"    border:none;\n"
"}")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget2.setGeometry(QtCore.QRect(19, 16, 201, 368))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setStyleSheet("#pushButton_2 {\n"
"  background-color: #296EFA; /* Green */\n"
"  border: none;\n"
"  color: #fff;\n"
"  padding: 10px 10px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    background-color: #1CE0B5; /* Green */\n"
"      border: none;\n"
"      color: #000059;\n"
"      padding: 10px 20px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      font-weight: 600;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem1)
        self.cb_employee = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_employee.setStyleSheet("#cb_employee {\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"    background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_employee.setChecked(True)
        self.cb_employee.setObjectName("cb_employee")
        self.verticalLayout_11.addWidget(self.cb_employee)
        self.cb_vehicle = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_vehicle.setStyleSheet("#cb_vehicle {\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"        background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_vehicle.setChecked(True)
        self.cb_vehicle.setObjectName("cb_vehicle")
        self.verticalLayout_11.addWidget(self.cb_vehicle)
        self.cb_warning = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_warning.setStyleSheet("#cb_warning {\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"        background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_warning.setChecked(True)
        self.cb_warning.setObjectName("cb_warning")
        self.verticalLayout_11.addWidget(self.cb_warning)
        self.cb_history = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_history.setStyleSheet("#cb_history{\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"        background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_history.setChecked(True)
        self.cb_history.setObjectName("cb_history")
        self.verticalLayout_11.addWidget(self.cb_history)
        self.cb_grid = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_grid.setStyleSheet("#cb_grid{\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"    background-color: #000059;\n"
"}    ")
        self.cb_grid.setChecked(True)
        self.cb_grid.setObjectName("cb_grid")
        self.verticalLayout_11.addWidget(self.cb_grid)
        self.cb_sensors = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_sensors.setEnabled(False)
        self.cb_sensors.setStyleSheet("#cb_sensors {\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"        background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_sensors.setObjectName("cb_sensors")
        self.verticalLayout_11.addWidget(self.cb_sensors)
        self.cb_dots = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_dots.setStyleSheet("#cb_dots {\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"    margin-bottom: 5px;\n"
"        background-color: rgba(1, 1, 118, 0);\n"
"}    ")
        self.cb_dots.setObjectName("cb_dots")
        self.verticalLayout_11.addWidget(self.cb_dots)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.le_map_width = QtWidgets.QLineEdit(self.layoutWidget2)
        self.le_map_width.setStyleSheet("#le_map_width {\n"
"    border-radius: 8px;\n"
"}")
        self.le_map_width.setObjectName("le_map_width")
        self.horizontalLayout_4.addWidget(self.le_map_width)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setStyleSheet("#label_23 {\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.le_map_hight = QtWidgets.QLineEdit(self.layoutWidget2)
        self.le_map_hight.setStyleSheet("#le_map_hight {\n"
"    border-radius: 8px;\n"
"}")
        self.le_map_hight.setObjectName("le_map_hight")
        self.horizontalLayout_4.addWidget(self.le_map_hight)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.pb_save_scale = QtWidgets.QPushButton(self.layoutWidget2)
        self.pb_save_scale.setObjectName("pb_save_scale")
        self.verticalLayout_11.addWidget(self.pb_save_scale)
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(17, 750, 211, 73))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_2)
        self.graphicsView_2.setSizeIncrement(QtCore.QSize(200, 50))
        self.graphicsView_2.setBaseSize(QtCore.QSize(200, 50))
        self.graphicsView_2.setStyleSheet("#graphicsView_2{\n"
"background-image: url(./data/LOGO.png);\n"
"background-repeat: no-repeat;\n"
"width: 200px;\n"
"height: 50px;\n"
"border:none;\n"
"}")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_7.addWidget(self.graphicsView_2)
        self.tb_main.addTab(self.tb_visualisation, "")
        self.tb_overview = QtWidgets.QWidget()
        self.tb_overview.setStyleSheet("tb_overview > #QPushButton {\n"
"  background-color: #296EFA; /* Green */\n"
"  border: none;\n"
"  color: #fff;\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-weight: 600;\n"
"}\n"
"#pushButton_2:hover {\n"
"    background-color: #1CE0B5; /* Green */\n"
"      border: none;\n"
"      color: #000059;\n"
"      padding: 10px 20px;\n"
"      text-align: center;\n"
"      text-decoration: none;\n"
"      font-weight: 600;\n"
"}")
        self.tb_overview.setObjectName("tb_overview")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tb_overview)
        self.groupBox_19.setGeometry(QtCore.QRect(239, 0, 931, 81))
        self.groupBox_19.setStyleSheet("#groupBox_19 {\n"
"    background-color: #000059;\n"
"border:none;\n"
"}")
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_19)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 28, 294, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.mqtt_layout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.mqtt_layout.setContentsMargins(5, 5, 0, 5)
        self.mqtt_layout.setObjectName("mqtt_layout")
        self.lb_mqtt_con_text = QtWidgets.QLabel(self.layoutWidget3)
        self.lb_mqtt_con_text.setToolTip("")
        self.lb_mqtt_con_text.setStyleSheet("#lb_mqtt_con_text {\n"
"    font-size: 14px;    \n"
"    font-weight: 600;\n"
"    color: #fff;\n"
"}")
        self.lb_mqtt_con_text.setObjectName("lb_mqtt_con_text")
        self.mqtt_layout.addWidget(self.lb_mqtt_con_text)
        self.lb_mqtt_con_state = QtWidgets.QLabel(self.layoutWidget3)
        self.lb_mqtt_con_state.setMinimumSize(QtCore.QSize(160, 20))
        self.lb_mqtt_con_state.setMaximumSize(QtCore.QSize(200, 30))
        self.lb_mqtt_con_state.setStyleSheet("#lb_mqtt_con_state {\n"
"    font-size: 14px;    \n"
"    font-weight: 600;\n"
"    color: #fff;\n"
"}")
        self.lb_mqtt_con_state.setText("")
        self.lb_mqtt_con_state.setObjectName("lb_mqtt_con_state")
        self.mqtt_layout.addWidget(self.lb_mqtt_con_state)
        self.gb_general_submenu = QtWidgets.QGroupBox(self.tb_overview)
        self.gb_general_submenu.setGeometry(QtCore.QRect(0, 0, 240, 810))
        self.gb_general_submenu.setMinimumSize(QtCore.QSize(240, 810))
        self.gb_general_submenu.setMaximumSize(QtCore.QSize(16777215, 810))
        self.gb_general_submenu.setStyleSheet("#gb_general_submenu {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.gb_general_submenu.setTitle("")
        self.gb_general_submenu.setObjectName("gb_general_submenu")
        self.groupBox = QtWidgets.QGroupBox(self.gb_general_submenu)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 220, 281))
        self.groupBox.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox.setStyleSheet("#groupBox {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    font-weight: 600;\n"
"}\n"
"#groupBox::Title {\n"
"    color: #fff;\n"
"    \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(8, 30, 201, 231))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.layout_sensors_config = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.layout_sensors_config.setContentsMargins(0, 0, 0, 0)
        self.layout_sensors_config.setObjectName("layout_sensors_config")
        self.btn_all_cal_search = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_cal_search.setWhatsThis("")
        self.btn_all_cal_search.setObjectName("btn_all_cal_search")
        self.layout_sensors_config.addWidget(self.btn_all_cal_search)
        self.btn_all_det_pose = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_det_pose.setWhatsThis("")
        self.btn_all_det_pose.setObjectName("btn_all_det_pose")
        self.layout_sensors_config.addWidget(self.btn_all_det_pose)
        self.btn_all_det_pose_human = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_det_pose_human.setWhatsThis("")
        self.btn_all_det_pose_human.setObjectName("btn_all_det_pose_human")
        self.layout_sensors_config.addWidget(self.btn_all_det_pose_human)
        self.btn_all_stop = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_stop.setObjectName("btn_all_stop")
        self.layout_sensors_config.addWidget(self.btn_all_stop)
        self.btn_reset_camera = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_reset_camera.setObjectName("btn_reset_camera")
        self.layout_sensors_config.addWidget(self.btn_reset_camera)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.layout_sensors_config.addWidget(self.label_3)
        self.btn_all_reboot = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_reboot.setEnabled(True)
        self.btn_all_reboot.setObjectName("btn_all_reboot")
        self.layout_sensors_config.addWidget(self.btn_all_reboot)
        self.btn_all_git_update = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_all_git_update.setEnabled(False)
        self.btn_all_git_update.setObjectName("btn_all_git_update")
        self.layout_sensors_config.addWidget(self.btn_all_git_update)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gb_general_submenu)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(17, 750, 211, 73))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        self.graphicsView_3.setSizeIncrement(QtCore.QSize(200, 50))
        self.graphicsView_3.setBaseSize(QtCore.QSize(200, 50))
        self.graphicsView_3.setStyleSheet("#graphicsView_3{\n"
"background-image: url(./data/LOGO.png);\n"
"background-repeat: no-repeat;\n"
"width: 200px;\n"
"height: 50px;\n"
"border:none;\n"
"}")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_16.addWidget(self.graphicsView_3)
        self.gb_video_record_2 = QtWidgets.QGroupBox(self.gb_general_submenu)
        self.gb_video_record_2.setGeometry(QtCore.QRect(10, 300, 220, 150))
        self.gb_video_record_2.setMinimumSize(QtCore.QSize(220, 150))
        self.gb_video_record_2.setMaximumSize(QtCore.QSize(220, 150))
        self.gb_video_record_2.setStyleSheet("\n"
"#gb_video_record_2 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}\n"
"\n"
"#gb_video_record_2::Title {\n"
"    color: #fff;\n"
"}")
        self.gb_video_record_2.setObjectName("gb_video_record_2")
        self.layoutWidget_8 = QtWidgets.QWidget(self.gb_video_record_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 25, 231, 111))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_15.setStyleSheet("#label_15 {\n"
"    color: #fff;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.le_video_filename_all = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.le_video_filename_all.setMaximumSize(QtCore.QSize(150, 20))
        self.le_video_filename_all.setStyleSheet("#lineEdit_4 {\n"
"    border-radius: 8px;\n"
"}")
        self.le_video_filename_all.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_video_filename_all.setObjectName("le_video_filename_all")
        self.horizontalLayout_16.addWidget(self.le_video_filename_all)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_34.setStyleSheet("#label_34 {\n"
"    color: #fff;\n"
"}")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_18.addWidget(self.label_34)
        self.le_video_duration_all = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.le_video_duration_all.setMaximumSize(QtCore.QSize(150, 20))
        self.le_video_duration_all.setStyleSheet("#lineEdit_5 {\n"
"    border-radius: 8px;\n"
"}")
        self.le_video_duration_all.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_video_duration_all.setObjectName("le_video_duration_all")
        self.horizontalLayout_18.addWidget(self.le_video_duration_all)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.btn_video_record_all = QtWidgets.QPushButton(self.layoutWidget_8)
        self.btn_video_record_all.setObjectName("btn_video_record_all")
        self.verticalLayout_10.addWidget(self.btn_video_record_all)
        self.layoutWidget5 = QtWidgets.QWidget(self.tb_overview)
        self.layoutWidget5.setGeometry(QtCore.QRect(260, 120, 881, 641))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_16 = QtWidgets.QGroupBox(self.layoutWidget5)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 600))
        self.groupBox_16.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox_16.setStyleSheet("#groupBox_16::Title {\n"
"    color: #000059;\n"
"}\n"
"\n"
"#groupBox_16 {\n"
"    font-weight: 600;\n"
"}")
        self.groupBox_16.setObjectName("groupBox_16")
        self.lw_sensors = QtWidgets.QListWidget(self.groupBox_16)
        self.lw_sensors.setGeometry(QtCore.QRect(20, 35, 390, 550))
        self.lw_sensors.setMinimumSize(QtCore.QSize(0, 550))
        self.lw_sensors.setMaximumSize(QtCore.QSize(390, 550))
        self.lw_sensors.setToolTip("")
        self.lw_sensors.setStyleSheet("QListWidget {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"}")
        self.lw_sensors.setObjectName("lw_sensors")
        self.horizontalLayout_5.addWidget(self.groupBox_16)
        self.groupBox_15 = QtWidgets.QGroupBox(self.layoutWidget5)
        self.groupBox_15.setMinimumSize(QtCore.QSize(0, 600))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox_15.setStyleSheet("#groupBox_15::Title {\n"
"    color: #000059;\n"
"}\n"
"\n"
"#groupBox_15 {\n"
"    font-weight: 600;\n"
"}")
        self.groupBox_15.setObjectName("groupBox_15")
        self.lw_vehicles = QtWidgets.QListWidget(self.groupBox_15)
        self.lw_vehicles.setGeometry(QtCore.QRect(20, 35, 390, 550))
        self.lw_vehicles.setMinimumSize(QtCore.QSize(0, 550))
        self.lw_vehicles.setMaximumSize(QtCore.QSize(390, 550))
        self.lw_vehicles.setToolTip("")
        self.lw_vehicles.setStyleSheet("#lw_vehicles {\n"
"background-color: white;\n"
"border-radius: 8px;\n"
"}")
        self.lw_vehicles.setObjectName("lw_vehicles")
        self.horizontalLayout_5.addWidget(self.groupBox_15)
        self.tb_main.addTab(self.tb_overview, "")
        self.tb_sensors = QtWidgets.QWidget()
        self.tb_sensors.setStyleSheet("QTabWidget QStackedWidget > QWidget  \n"
"{\n"
"    background-color: #fff;\n"
"}")
        self.tb_sensors.setObjectName("tb_sensors")
        self.tb_sensors_submenu = QtWidgets.QTabWidget(self.tb_sensors)
        self.tb_sensors_submenu.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.tb_sensors_submenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tb_sensors_submenu.setAutoFillBackground(False)
        self.tb_sensors_submenu.setStyleSheet("QWidget{\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#tb_sensors_submenu {\n"
"    background-color: red;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tb_sensors_submenu.setTabPosition(QtWidgets.QTabWidget.West)
        self.tb_sensors_submenu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tb_sensors_submenu.setElideMode(QtCore.Qt.ElideMiddle)
        self.tb_sensors_submenu.setDocumentMode(True)
        self.tb_sensors_submenu.setMovable(False)
        self.tb_sensors_submenu.setTabBarAutoHide(False)
        self.tb_sensors_submenu.setObjectName("tb_sensors_submenu")
        self.tb_sensors_general = QtWidgets.QWidget()
        self.tb_sensors_general.setStyleSheet("")
        self.tb_sensors_general.setObjectName("tb_sensors_general")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tb_sensors_general)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 0, 270, 805))
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 805))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 805))
        self.groupBox_9.setStyleSheet("#groupBox_9 {\n"
"    background-color: #000059;\n"
"border: none;\n"
"}")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 250, 300))
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 250))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 300))
        self.groupBox_2.setStyleSheet("\n"
"#groupBox_2::title {\n"
"    color: #fff;\n"
"}\n"
"#groupBox_2 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 34, 231, 251))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setStyleSheet("#label_4 {\n"
"    color: #fff;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("#label_5 {\n"
"    color: #fff;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.btn_single_det_pose = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_det_pose.setObjectName("btn_single_det_pose")
        self.verticalLayout_9.addWidget(self.btn_single_det_pose)
        self.btn_single_det_pose_human = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_det_pose_human.setObjectName("btn_single_det_pose_human")
        self.verticalLayout_9.addWidget(self.btn_single_det_pose_human)
        self.btn_single_cal_calibrate = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_cal_calibrate.setObjectName("btn_single_cal_calibrate")
        self.verticalLayout_9.addWidget(self.btn_single_cal_calibrate)
        self.btn_single_cal_search = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_cal_search.setObjectName("btn_single_cal_search")
        self.verticalLayout_9.addWidget(self.btn_single_cal_search)
        self.btn_single_stop = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_stop.setObjectName("btn_single_stop")
        self.verticalLayout_9.addWidget(self.btn_single_stop)
        self.btn_single_reset_cam = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_single_reset_cam.setObjectName("btn_single_reset_cam")
        self.verticalLayout_9.addWidget(self.btn_single_reset_cam)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 315, 250, 150))
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 150))
        self.groupBox_4.setMaximumSize(QtCore.QSize(250, 150))
        self.groupBox_4.setStyleSheet("#groupBox_4 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}\n"
"#groupBox_4::Title {\n"
"    color: #fff;\n"
"}")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 231, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_single_reboot = QtWidgets.QPushButton(self.layoutWidget_4)
        self.btn_single_reboot.setEnabled(True)
        self.btn_single_reboot.setObjectName("btn_single_reboot")
        self.verticalLayout_2.addWidget(self.btn_single_reboot)
        self.btn_single_git_update = QtWidgets.QPushButton(self.layoutWidget_4)
        self.btn_single_git_update.setEnabled(True)
        self.btn_single_git_update.setObjectName("btn_single_git_update")
        self.verticalLayout_2.addWidget(self.btn_single_git_update)
        self.gb_video_record = QtWidgets.QGroupBox(self.groupBox_9)
        self.gb_video_record.setGeometry(QtCore.QRect(10, 470, 250, 150))
        self.gb_video_record.setMinimumSize(QtCore.QSize(250, 150))
        self.gb_video_record.setMaximumSize(QtCore.QSize(250, 150))
        self.gb_video_record.setStyleSheet("\n"
"#gb_video_record {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}\n"
"\n"
"#gb_video_record::Title {\n"
"    color: #fff;\n"
"}")
        self.gb_video_record.setObjectName("gb_video_record")
        self.layoutWidget_5 = QtWidgets.QWidget(self.gb_video_record)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 25, 231, 111))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_10.setStyleSheet("#label_10 {\n"
"    color: #fff;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.le_video_filename = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.le_video_filename.setMaximumSize(QtCore.QSize(150, 20))
        self.le_video_filename.setStyleSheet("#lineEdit_4 {\n"
"    border-radius: 8px;\n"
"}")
        self.le_video_filename.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_video_filename.setObjectName("le_video_filename")
        self.horizontalLayout_10.addWidget(self.le_video_filename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_11.setStyleSheet("#label_11 {\n"
"    color: #fff;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.le_video_duration = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.le_video_duration.setMaximumSize(QtCore.QSize(150, 20))
        self.le_video_duration.setStyleSheet("#lineEdit_5 {\n"
"    border-radius: 8px;\n"
"}")
        self.le_video_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_video_duration.setObjectName("le_video_duration")
        self.horizontalLayout_11.addWidget(self.le_video_duration)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.btn_video_record = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_video_record.setObjectName("btn_video_record")
        self.verticalLayout_4.addWidget(self.btn_video_record)
        self.tb_sensors_submenu.addTab(self.tb_sensors_general, "")
        self.tb_sensors_image = QtWidgets.QWidget()
        self.tb_sensors_image.setObjectName("tb_sensors_image")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tb_sensors_image)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 0, 270, 801))
        self.groupBox_13.setMinimumSize(QtCore.QSize(270, 0))
        self.groupBox_13.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_13.setStyleSheet("#groupBox_13 {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 250, 155))
        self.groupBox_7.setMinimumSize(QtCore.QSize(250, 100))
        self.groupBox_7.setMaximumSize(QtCore.QSize(250, 160))
        self.groupBox_7.setStyleSheet("#groupBox_7::title {\n"
"    color: #fff;\n"
"}\n"
"#groupBox_7 {\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"")
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 231, 121))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.le_mask_path = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le_mask_path.setStyleSheet("#le_mask_path {\n"
"    border-radius: 8px;\n"
"}")
        self.le_mask_path.setObjectName("le_mask_path")
        self.verticalLayout_12.addWidget(self.le_mask_path)
        self.btn_select_mask = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_select_mask.setObjectName("btn_select_mask")
        self.verticalLayout_12.addWidget(self.btn_select_mask)
        self.btn_upload_mask = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_upload_mask.setObjectName("btn_upload_mask")
        self.verticalLayout_12.addWidget(self.btn_upload_mask)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 180, 250, 150))
        self.groupBox_8.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(250, 150))
        self.groupBox_8.setStyleSheet("#groupBox_8::title {\n"
"    color: #fff;\n"
"}\n"
"#groupBox_8 {\n"
"    font-weight: 600;\n"
"    \n"
"\n"
"}\n"
"")
        self.groupBox_8.setObjectName("groupBox_8")
        self.rb_image_merged = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_image_merged.setGeometry(QtCore.QRect(10, 117, 99, 20))
        self.rb_image_merged.setStyleSheet("#rb_image_merged {\n"
"    font-weight: 500;\n"
"    color: #fff;\n"
"border:none;\n"
"}")
        self.rb_image_merged.setObjectName("rb_image_merged")
        self.rb_image_normal = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_image_normal.setGeometry(QtCore.QRect(10, 57, 99, 20))
        self.rb_image_normal.setStyleSheet("#rb_image_normal {\n"
"    font-weight: 500;\n"
"    color: #fff;\n"
"    border:none;\n"
"}")
        self.rb_image_normal.setChecked(True)
        self.rb_image_normal.setObjectName("rb_image_normal")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_16.setStyleSheet("#label_16 {\n"
"    font-weight: 500;\n"
"    color: #fff;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.rb_image_mask = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_image_mask.setGeometry(QtCore.QRect(10, 87, 99, 20))
        self.rb_image_mask.setStyleSheet("#rb_image_mask {\n"
"    font-weight: 500;\n"
"    color: #fff;\n"
"border:none;\n"
"}")
        self.rb_image_mask.setObjectName("rb_image_mask")
        self.tb_sensors_submenu.addTab(self.tb_sensors_image, "")
        self.tb_sensors_calib = QtWidgets.QWidget()
        self.tb_sensors_calib.setObjectName("tb_sensors_calib")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tb_sensors_calib)
        self.groupBox_14.setGeometry(QtCore.QRect(0, -10, 270, 811))
        self.groupBox_14.setMinimumSize(QtCore.QSize(270, 0))
        self.groupBox_14.setMaximumSize(QtCore.QSize(270, 16777215))
        self.groupBox_14.setStyleSheet("#groupBox_14 {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.vslam_groupe = QtWidgets.QGroupBox(self.groupBox_14)
        self.vslam_groupe.setGeometry(QtCore.QRect(10, 450, 250, 270))
        self.vslam_groupe.setMinimumSize(QtCore.QSize(250, 0))
        self.vslam_groupe.setMaximumSize(QtCore.QSize(250, 270))
        self.vslam_groupe.setStyleSheet("#vslam_groupe {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"\n"
"}\n"
"\n"
"#vslam_groupe::Title {\n"
"    color: #fff;\n"
"}\n"
"\n"
"")
        self.vslam_groupe.setObjectName("vslam_groupe")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.vslam_groupe)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 231, 221))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_vslam_start = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_vslam_start.setEnabled(False)
        self.btn_vslam_start.setMaximumSize(QtCore.QSize(230, 16777215))
        self.btn_vslam_start.setObjectName("btn_vslam_start")
        self.verticalLayout_5.addWidget(self.btn_vslam_start)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setMaximumSize(QtCore.QSize(82, 16777215))
        self.label_12.setStyleSheet("#label_12 {\n"
"    color: #fff;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.le_vslam_scale = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.le_vslam_scale.setEnabled(False)
        self.le_vslam_scale.setMaximumSize(QtCore.QSize(90, 20))
        self.le_vslam_scale.setStyleSheet("#le_vslam_scale {\n"
"    border-radius: 8px;\n"
"}")
        self.le_vslam_scale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_vslam_scale.setObjectName("le_vslam_scale")
        self.horizontalLayout_12.addWidget(self.le_vslam_scale)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_13.setMinimumSize(QtCore.QSize(82, 0))
        self.label_13.setMaximumSize(QtCore.QSize(82, 16777215))
        self.label_13.setStyleSheet("#label_13 {\n"
"    color: #fff;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.le_vslam_offset_x = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.le_vslam_offset_x.setEnabled(False)
        self.le_vslam_offset_x.setMinimumSize(QtCore.QSize(80, 0))
        self.le_vslam_offset_x.setMaximumSize(QtCore.QSize(90, 20))
        self.le_vslam_offset_x.setStyleSheet("#le_vslam_offset_x {\n"
"    border-radius: 8px;\n"
"}")
        self.le_vslam_offset_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_vslam_offset_x.setObjectName("le_vslam_offset_x")
        self.horizontalLayout_13.addWidget(self.le_vslam_offset_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_14.setMinimumSize(QtCore.QSize(82, 0))
        self.label_14.setMaximumSize(QtCore.QSize(82, 16777215))
        self.label_14.setStyleSheet("#label_14 {\n"
"    color: #fff;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.le_vslam_offset_y = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.le_vslam_offset_y.setMinimumSize(QtCore.QSize(90, 0))
        self.le_vslam_offset_y.setMaximumSize(QtCore.QSize(90, 20))
        self.le_vslam_offset_y.setStyleSheet("#le_vslam_offset_y {\n"
"    border-radius: 8px;\n"
"}")
        self.le_vslam_offset_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_vslam_offset_y.setObjectName("le_vslam_offset_y")
        self.horizontalLayout_14.addWidget(self.le_vslam_offset_y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.btn_vslam_update = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_vslam_update.setMaximumSize(QtCore.QSize(230, 16777215))
        self.btn_vslam_update.setObjectName("btn_vslam_update")
        self.verticalLayout_5.addWidget(self.btn_vslam_update)
        self.calib_groupe = QtWidgets.QGroupBox(self.groupBox_14)
        self.calib_groupe.setGeometry(QtCore.QRect(10, 20, 250, 420))
        self.calib_groupe.setMinimumSize(QtCore.QSize(250, 420))
        self.calib_groupe.setMaximumSize(QtCore.QSize(240, 420))
        self.calib_groupe.setStyleSheet("#calib_groupe::Title {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#calib_groupe {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"\n"
"}\n"
"\n"
"")
        self.calib_groupe.setObjectName("calib_groupe")
        self.layoutWidget7 = QtWidgets.QWidget(self.calib_groupe)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 30, 231, 381))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_single_cal_search_2 = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_single_cal_search_2.setObjectName("btn_single_cal_search_2")
        self.verticalLayout_13.addWidget(self.btn_single_cal_search_2)
        self.btn_single_cal_calibrate_2 = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_single_cal_calibrate_2.setObjectName("btn_single_cal_calibrate_2")
        self.verticalLayout_13.addWidget(self.btn_single_cal_calibrate_2)
        self.btn_single_stop_2 = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_single_stop_2.setObjectName("btn_single_stop_2")
        self.verticalLayout_13.addWidget(self.btn_single_stop_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_24.setStyleSheet("#label_24 {\n"
"    color: #fff;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_25.setMinimumSize(QtCore.QSize(0, 15))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setStyleSheet("#label_25 {\n"
"    color: #fff;\n"
"}")
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_7.setStyleSheet("#label_7 {\n"
"    color: #fff;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.le_calibration_x = QtWidgets.QLineEdit(self.layoutWidget7)
        self.le_calibration_x.setMaximumSize(QtCore.QSize(190, 20))
        self.le_calibration_x.setStyleSheet("#le_calibration_x {\n"
"    border-radius: 8px;\n"
"}")
        self.le_calibration_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_calibration_x.setObjectName("le_calibration_x")
        self.horizontalLayout_6.addWidget(self.le_calibration_x)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_8.setStyleSheet("#label_8 {\n"
"    color: #fff;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.le_calibration_y = QtWidgets.QLineEdit(self.layoutWidget7)
        self.le_calibration_y.setMaximumSize(QtCore.QSize(190, 20))
        self.le_calibration_y.setStyleSheet("#le_calibration_y {\n"
"    border-radius: 8px;\n"
"}")
        self.le_calibration_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_calibration_y.setObjectName("le_calibration_y")
        self.horizontalLayout_8.addWidget(self.le_calibration_y)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.btn_cal_send_position = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_cal_send_position.setMaximumSize(QtCore.QSize(230, 16777215))
        self.btn_cal_send_position.setObjectName("btn_cal_send_position")
        self.verticalLayout_13.addWidget(self.btn_cal_send_position)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_9.setStyleSheet("#label_9 {\n"
"    color: #fff;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.le_marker_size = QtWidgets.QLineEdit(self.layoutWidget7)
        self.le_marker_size.setMaximumSize(QtCore.QSize(190, 20))
        self.le_marker_size.setStyleSheet("#le_marker_size {\n"
"    border-radius: 8px;\n"
"}")
        self.le_marker_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_marker_size.setObjectName("le_marker_size")
        self.horizontalLayout_7.addWidget(self.le_marker_size)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_cal_send_markersize = QtWidgets.QPushButton(self.layoutWidget7)
        self.btn_cal_send_markersize.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_cal_send_markersize.setMaximumSize(QtCore.QSize(230, 16777215))
        self.btn_cal_send_markersize.setObjectName("btn_cal_send_markersize")
        self.verticalLayout_3.addWidget(self.btn_cal_send_markersize)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox.setStyleSheet("#checkBox {\n"
"    border: none;\n"
"    color: #fff;\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_13.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem4)
        self.tb_sensors_submenu.addTab(self.tb_sensors_calib, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 0, 270, 801))
        self.groupBox_11.setMinimumSize(QtCore.QSize(270, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(270, 16777215))
        self.groupBox_11.setStyleSheet("#groupBox_11 {\n"
"    background-color: rgba(0, 0, 85, 1);\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 10, 250, 450))
        self.groupBox_17.setMinimumSize(QtCore.QSize(250, 450))
        self.groupBox_17.setMaximumSize(QtCore.QSize(250, 450))
        self.groupBox_17.setStyleSheet("#groupBox_17::Title \n"
"{ \n"
"    color: #fff;\n"
"}\n"
"\n"
"#groupBox_17 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}")
        self.groupBox_17.setObjectName("groupBox_17")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_17)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 30, 231, 396))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_2.setStyleSheet("#label_2 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_35.addWidget(self.label_2)
        self.cb_verbose_active = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cb_verbose_active.setEnabled(False)
        self.cb_verbose_active.setMinimumSize(QtCore.QSize(80, 0))
        self.cb_verbose_active.setStyleSheet("#cb_verbose_active{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.cb_verbose_active.setObjectName("cb_verbose_active")
        self.horizontalLayout_35.addWidget(self.cb_verbose_active)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_17.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_17.setStyleSheet("#label_17{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_34.addWidget(self.label_17)
        self.le_intrinsic_file = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_intrinsic_file.setEnabled(False)
        self.le_intrinsic_file.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_intrinsic_file.setStyleSheet("#le_intrinsic_file {\n"
"    border-radius: 6px; \n"
"}")
        self.le_intrinsic_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_intrinsic_file.setObjectName("le_intrinsic_file")
        self.horizontalLayout_34.addWidget(self.le_intrinsic_file)
        self.verticalLayout_15.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_19.setStyleSheet("#label_19{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_33.addWidget(self.label_19)
        self.le_cam_edit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_cam_edit.setEnabled(False)
        self.le_cam_edit.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_cam_edit.setStyleSheet("#le_cam_edit {\n"
"    border-radius: 6px; \n"
"}")
        self.le_cam_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_cam_edit.setObjectName("le_cam_edit")
        self.horizontalLayout_33.addWidget(self.le_cam_edit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_27.setMinimumSize(QtCore.QSize(70, 0))
        self.label_27.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_27.setStyleSheet("#label_27{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_32.addWidget(self.label_27)
        self.le_cam_res_length = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_cam_res_length.setEnabled(False)
        self.le_cam_res_length.setMinimumSize(QtCore.QSize(45, 0))
        self.le_cam_res_length.setMaximumSize(QtCore.QSize(30, 16777215))
        self.le_cam_res_length.setStyleSheet("#le_cam_res_length {\n"
"    border-radius: 6px; \n"
"}")
        self.le_cam_res_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_cam_res_length.setObjectName("le_cam_res_length")
        self.horizontalLayout_32.addWidget(self.le_cam_res_length)
        self.le_cam_res_hight = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_cam_res_hight.setEnabled(False)
        self.le_cam_res_hight.setMinimumSize(QtCore.QSize(45, 0))
        self.le_cam_res_hight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_cam_res_hight.setStyleSheet("#le_cam_res_hight {\n"
"    border-radius: 6px; \n"
"}")
        self.le_cam_res_hight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_cam_res_hight.setObjectName("le_cam_res_hight")
        self.horizontalLayout_32.addWidget(self.le_cam_res_hight)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_26.setStyleSheet("#label_26{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_31.addWidget(self.label_26)
        self.le_framerate = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_framerate.setEnabled(False)
        self.le_framerate.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_framerate.setStyleSheet("#le_framerate{\n"
"    border-radius: 6px; \n"
"}")
        self.le_framerate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_framerate.setObjectName("le_framerate")
        self.horizontalLayout_31.addWidget(self.le_framerate)
        self.verticalLayout_15.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_29.setMinimumSize(QtCore.QSize(80, 0))
        self.label_29.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_29.setStyleSheet("#label_29{\n"
"background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_30.addWidget(self.label_29)
        self.cb_flip_cam = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cb_flip_cam.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cb_flip_cam.setStyleSheet("#cb_flip_cam{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.cb_flip_cam.setObjectName("cb_flip_cam")
        self.horizontalLayout_30.addWidget(self.cb_flip_cam)
        self.verticalLayout_15.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_30.setStyleSheet("#label_30{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_29.addWidget(self.label_30)
        self.le_broker = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_broker.setEnabled(False)
        self.le_broker.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_broker.setStyleSheet("#le_broker{\n"
"    border-radius: 6px; \n"
"}")
        self.le_broker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_broker.setObjectName("le_broker")
        self.horizontalLayout_29.addWidget(self.le_broker)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_28.setStyleSheet("#label_28{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.le_database = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_database.setEnabled(False)
        self.le_database.setMinimumSize(QtCore.QSize(100, 0))
        self.le_database.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_database.setStyleSheet("#le_database {\n"
"    border-radius: 6px; \n"
"}")
        self.le_database.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_database.setObjectName("le_database")
        self.horizontalLayout_28.addWidget(self.le_database)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_31.setMinimumSize(QtCore.QSize(80, 0))
        self.label_31.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_31.setStyleSheet("#label_31{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_27.addWidget(self.label_31)
        self.cb_undistort = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cb_undistort.setEnabled(False)
        self.cb_undistort.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cb_undistort.setStyleSheet("#cb_undistort{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.cb_undistort.setObjectName("cb_undistort")
        self.horizontalLayout_27.addWidget(self.cb_undistort)
        self.verticalLayout_15.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_32.setMaximumSize(QtCore.QSize(115, 16777215))
        self.label_32.setStyleSheet("#label_32{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_26.addWidget(self.label_32)
        self.cb_mask = QtWidgets.QCheckBox(self.layoutWidget8)
        self.cb_mask.setEnabled(False)
        self.cb_mask.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cb_mask.setStyleSheet("#cb_mask{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.cb_mask.setObjectName("cb_mask")
        self.horizontalLayout_26.addWidget(self.cb_mask)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_33.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_33.setStyleSheet("\n"
"#label_33{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 500;\n"
"    padding: 3px;\n"
"}    ")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_2.addWidget(self.label_33)
        self.le_mask_file = QtWidgets.QLineEdit(self.layoutWidget8)
        self.le_mask_file.setEnabled(False)
        self.le_mask_file.setMinimumSize(QtCore.QSize(100, 0))
        self.le_mask_file.setMaximumSize(QtCore.QSize(105, 16777215))
        self.le_mask_file.setStyleSheet("#le_mask_file {\n"
"    border-radius: 6px; \n"
"}")
        self.le_mask_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_mask_file.setObjectName("le_mask_file")
        self.horizontalLayout_2.addWidget(self.le_mask_file)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.tb_sensors_submenu.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tb_sensors_submenu.addTab(self.tab_3, "")
        self.layoutWidget9 = QtWidgets.QWidget(self.tb_sensors)
        self.layoutWidget9.setGeometry(QtCore.QRect(335, 156, 804, 646))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget9)
        self.graphicsView.setMinimumSize(QtCore.QSize(800, 604))
        self.graphicsView.setMaximumSize(QtCore.QSize(800, 604))
        self.graphicsView.setStyleSheet("#graphicsView {\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"}")
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_18.addWidget(self.graphicsView)
        self.verticalLayout_21.addLayout(self.verticalLayout_18)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tb_sensors)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(67, 750, 211, 73))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_6.setSizeIncrement(QtCore.QSize(200, 50))
        self.graphicsView_6.setBaseSize(QtCore.QSize(200, 50))
        self.graphicsView_6.setStyleSheet("#graphicsView_6{\n"
"background-image: url(./data/LOGO.png);\n"
"background-repeat: no-repeat;\n"
"width: 200px;\n"
"height: 50px;\n"
"border:none;\n"
"}")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_23.addWidget(self.graphicsView_6)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tb_sensors)
        self.groupBox_12.setGeometry(QtCore.QRect(305, 0, 881, 160))
        self.groupBox_12.setMinimumSize(QtCore.QSize(220, 160))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 160))
        self.groupBox_12.setStyleSheet("#groupBox_12 {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget_6.setGeometry(QtCore.QRect(80, 6, 691, 151))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget_6)
        self.groupBox_5.setMaximumSize(QtCore.QSize(330, 140))
        self.groupBox_5.setStyleSheet("#groupBox_5 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#groupBox_5::Title {\n"
"    color: #fff;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 27, 291, 111))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.cb_sensor = QtWidgets.QComboBox(self.layoutWidget_7)
        self.cb_sensor.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_sensor.setMaximumSize(QtCore.QSize(200, 30))
        self.cb_sensor.setObjectName("cb_sensor")
        self.verticalLayout_17.addWidget(self.cb_sensor)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lb_ip_text = QtWidgets.QLabel(self.layoutWidget_7)
        self.lb_ip_text.setMaximumSize(QtCore.QSize(40, 20))
        self.lb_ip_text.setStyleSheet("#lb_ip_text {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.lb_ip_text.setObjectName("lb_ip_text")
        self.horizontalLayout_20.addWidget(self.lb_ip_text)
        self.lb_ip = QtWidgets.QLabel(self.layoutWidget_7)
        self.lb_ip.setMinimumSize(QtCore.QSize(80, 20))
        self.lb_ip.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lb_ip.setStyleSheet("#lb_ip {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.lb_ip.setText("")
        self.lb_ip.setObjectName("lb_ip")
        self.horizontalLayout_20.addWidget(self.lb_ip)
        spacerItem5 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lb_mode_text = QtWidgets.QLabel(self.layoutWidget_7)
        self.lb_mode_text.setMaximumSize(QtCore.QSize(47, 16777215))
        self.lb_mode_text.setStyleSheet("#lb_mode_text {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.lb_mode_text.setObjectName("lb_mode_text")
        self.horizontalLayout_19.addWidget(self.lb_mode_text)
        self.lb_mode = QtWidgets.QLabel(self.layoutWidget_7)
        self.lb_mode.setStyleSheet("#lb_mode{\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.lb_mode.setText("")
        self.lb_mode.setObjectName("lb_mode")
        self.horizontalLayout_19.addWidget(self.lb_mode)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23.addWidget(self.groupBox_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget_6)
        self.groupBox_6.setMinimumSize(QtCore.QSize(330, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(0, 140))
        self.groupBox_6.setStyleSheet("#groupBox_6::Title {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#groupBox_6{\n"
"    font-weight:600;\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_18.setStyleSheet("#label_18 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"}")
        self.label_18.setLineWidth(1)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pb_load_ing_general = QtWidgets.QProgressBar(self.groupBox_6)
        self.pb_load_ing_general.setEnabled(False)
        self.pb_load_ing_general.setProperty("value", 0)
        self.pb_load_ing_general.setTextVisible(False)
        self.pb_load_ing_general.setObjectName("pb_load_ing_general")
        self.verticalLayout_6.addWidget(self.pb_load_ing_general)
        self.horizontalLayout_23.addWidget(self.groupBox_6)
        self.tb_main.addTab(self.tb_sensors, "")
        self.tb_vehicles = QtWidgets.QWidget()
        self.tb_vehicles.setObjectName("tb_vehicles")
        self.tb_main.addTab(self.tb_vehicles, "")
        self.tb_system = QtWidgets.QWidget()
        self.tb_system.setObjectName("tb_system")
        self.layoutWidget10 = QtWidgets.QWidget(self.tb_system)
        self.layoutWidget10.setGeometry(QtCore.QRect(300, 21, 804, 761))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem7)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget10)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(800, 700))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(700, 700))
        self.plainTextEdit.setStyleSheet("#plainTextEdit {\n"
"\n"
"    border-radius: 12px;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_14.addWidget(self.plainTextEdit)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem8 = QtWidgets.QSpacerItem(560, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget10)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(250, 30))
        self.pushButton_5.setStyleSheet("#pushButton_5 {\n"
"    font-weight: 600; \n"
"    color: #000059;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_15.addWidget(self.pushButton_5)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17.addLayout(self.verticalLayout_14)
        self.gb_system_submenu = QtWidgets.QGroupBox(self.tb_system)
        self.gb_system_submenu.setGeometry(QtCore.QRect(0, 0, 240, 810))
        self.gb_system_submenu.setMinimumSize(QtCore.QSize(240, 810))
        self.gb_system_submenu.setMaximumSize(QtCore.QSize(16777215, 810))
        self.gb_system_submenu.setStyleSheet("#gb_system_submenu {\n"
"    background-color: #000059;\n"
"    border: none;\n"
"}")
        self.gb_system_submenu.setTitle("")
        self.gb_system_submenu.setObjectName("gb_system_submenu")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gb_system_submenu)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 221, 220))
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 220))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 220))
        self.groupBox_3.setStyleSheet("#groupBox_3 {\n"
"    background-color: rgba(0, 0, 85, 0);\n"
"    font-weight: 600;\n"
"}\n"
"#groupBox_3::Title {\n"
"    color: #fff;\n"
"    \n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 30, 201, 181))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_6.setStyleSheet("#label_6 {\n"
"    color: #fff;\n"
"    font-weight: 600;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.cb_system_topic = QtWidgets.QComboBox(self.layoutWidget11)
        self.cb_system_topic.setMinimumSize(QtCore.QSize(190, 0))
        self.cb_system_topic.setObjectName("cb_system_topic")
        self.verticalLayout_8.addWidget(self.cb_system_topic)
        self.pb_system_select_file = QtWidgets.QPushButton(self.layoutWidget11)
        self.pb_system_select_file.setEnabled(False)
        self.pb_system_select_file.setObjectName("pb_system_select_file")
        self.verticalLayout_8.addWidget(self.pb_system_select_file)
        self.le_system_file_path = QtWidgets.QLineEdit(self.layoutWidget11)
        self.le_system_file_path.setEnabled(False)
        self.le_system_file_path.setMaximumSize(QtCore.QSize(190, 16777215))
        self.le_system_file_path.setObjectName("le_system_file_path")
        self.verticalLayout_8.addWidget(self.le_system_file_path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_record_start = QtWidgets.QPushButton(self.layoutWidget11)
        self.pb_record_start.setEnabled(False)
        self.pb_record_start.setObjectName("pb_record_start")
        self.horizontalLayout.addWidget(self.pb_record_start)
        self.pb_record_stop = QtWidgets.QPushButton(self.layoutWidget11)
        self.pb_record_stop.setEnabled(False)
        self.pb_record_stop.setObjectName("pb_record_stop")
        self.horizontalLayout.addWidget(self.pb_record_stop)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.gb_system_submenu)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(17, 750, 211, 73))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_6)
        self.graphicsView_7.setSizeIncrement(QtCore.QSize(200, 50))
        self.graphicsView_7.setBaseSize(QtCore.QSize(200, 50))
        self.graphicsView_7.setStyleSheet("#graphicsView_7{\n"
"background-image: url(./data/LOGO.png);\n"
"background-repeat: no-repeat;\n"
"width: 200px;\n"
"height: 50px;\n"
"border:none;\n"
"}")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.verticalLayout_24.addWidget(self.graphicsView_7)
        self.tb_main.addTab(self.tb_system, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tb_main.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tb_main, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tb_main.setCurrentIndex(0)
        self.tb_sensors_submenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ProSuite by probility"))
        self.tb_main.setAccessibleName(_translate("Form", "widget_bg"))
        self.label_20.setText(_translate("Form", "People detected:"))
        self.lb_stat_employee.setText(_translate("Form", "0"))
        self.label_21.setText(_translate("Form", "Vehicle detected:"))
        self.lb_stat_vehicle.setText(_translate("Form", "0"))
        self.label_22.setText(_translate("Form", "Warnings today:"))
        self.lb_stat_warnings.setText(_translate("Form", "0"))
        self.pushButton_2.setText(_translate("Form", "Load image"))
        self.cb_employee.setText(_translate("Form", "Humans"))
        self.cb_vehicle.setText(_translate("Form", "Vehicles"))
        self.cb_warning.setText(_translate("Form", "Warnings"))
        self.cb_history.setText(_translate("Form", "History"))
        self.cb_grid.setText(_translate("Form", "Grid"))
        self.cb_sensors.setText(_translate("Form", "Sensors"))
        self.cb_dots.setText(_translate("Form", "Dots"))
        self.label_23.setText(_translate("Form", "x"))
        self.pb_save_scale.setText(_translate("Form", "Scale map"))
        self.tb_main.setTabText(self.tb_main.indexOf(self.tb_visualisation), _translate("Form", "Visualisation"))
        self.lb_mqtt_con_text.setText(_translate("Form", "MQTT Conection:"))
        self.groupBox.setTitle(_translate("Form", "Sensors settings"))
        self.btn_all_cal_search.setText(_translate("Form", "calibration - search"))
        self.btn_all_det_pose.setText(_translate("Form", "detection"))
        self.btn_all_det_pose_human.setText(_translate("Form", "deteciton - human"))
        self.btn_all_stop.setText(_translate("Form", "stop"))
        self.btn_reset_camera.setText(_translate("Form", "reset camera"))
        self.label_3.setText(_translate("Form", "experimental:"))
        self.btn_all_reboot.setText(_translate("Form", "reboot"))
        self.btn_all_git_update.setText(_translate("Form", "git autoupdate"))
        self.gb_video_record_2.setTitle(_translate("Form", "Video record:"))
        self.label_15.setText(_translate("Form", "Filename:"))
        self.le_video_filename_all.setText(_translate("Form", "default"))
        self.label_34.setText(_translate("Form", "Duration [s]:"))
        self.le_video_duration_all.setText(_translate("Form", "20"))
        self.btn_video_record_all.setText(_translate("Form", "Record"))
        self.groupBox_16.setTitle(_translate("Form", "Sensor - List"))
        self.groupBox_15.setTitle(_translate("Form", "Vehicle - List"))
        self.tb_main.setTabText(self.tb_main.indexOf(self.tb_overview), _translate("Form", "Overview"))
        self.groupBox_2.setTitle(_translate("Form", "Detection:"))
        self.label_4.setText(_translate("Form", "Vision:"))
        self.label_5.setText(_translate("Form", "False"))
        self.btn_single_det_pose.setText(_translate("Form", "detection"))
        self.btn_single_det_pose_human.setText(_translate("Form", "detection - human"))
        self.btn_single_cal_calibrate.setText(_translate("Form", "calibration - calibrate"))
        self.btn_single_cal_search.setText(_translate("Form", "calibration - search"))
        self.btn_single_stop.setText(_translate("Form", "stop"))
        self.btn_single_reset_cam.setText(_translate("Form", "Reset camera"))
        self.groupBox_4.setTitle(_translate("Form", "Experimental:"))
        self.btn_single_reboot.setText(_translate("Form", "reboot"))
        self.btn_single_git_update.setText(_translate("Form", "git autoupdate"))
        self.gb_video_record.setTitle(_translate("Form", "Video record:"))
        self.label_10.setText(_translate("Form", "Filename:"))
        self.le_video_filename.setText(_translate("Form", "default"))
        self.label_11.setText(_translate("Form", "Duration [s]:"))
        self.le_video_duration.setText(_translate("Form", "20"))
        self.btn_video_record.setText(_translate("Form", "Record"))
        self.tb_sensors_submenu.setTabText(self.tb_sensors_submenu.indexOf(self.tb_sensors_general), _translate("Form", "General"))
        self.groupBox_7.setTitle(_translate("Form", "Mask options:"))
        self.btn_select_mask.setText(_translate("Form", "Select mask"))
        self.btn_upload_mask.setText(_translate("Form", "Upload mask"))
        self.groupBox_8.setTitle(_translate("Form", "Display options:"))
        self.rb_image_merged.setText(_translate("Form", "Merged"))
        self.rb_image_normal.setText(_translate("Form", "Normal"))
        self.label_16.setText(_translate("Form", "Choose view mode:"))
        self.rb_image_mask.setText(_translate("Form", "Mask"))
        self.tb_sensors_submenu.setTabText(self.tb_sensors_submenu.indexOf(self.tb_sensors_image), _translate("Form", "Mask"))
        self.vslam_groupe.setTitle(_translate("Form", "VSLAM"))
        self.btn_vslam_start.setText(_translate("Form", "Start"))
        self.label_12.setText(_translate("Form", "Scale:"))
        self.le_vslam_scale.setText(_translate("Form", "1.0"))
        self.label_13.setText(_translate("Form", "X offset [m]:"))
        self.le_vslam_offset_x.setText(_translate("Form", "0.0"))
        self.label_14.setText(_translate("Form", "Y offset [m]:"))
        self.le_vslam_offset_y.setText(_translate("Form", "0.0"))
        self.btn_vslam_update.setText(_translate("Form", "Update"))
        self.calib_groupe.setTitle(_translate("Form", "Calibration"))
        self.btn_single_cal_search_2.setText(_translate("Form", "search"))
        self.btn_single_cal_calibrate_2.setText(_translate("Form", "calibrate"))
        self.btn_single_stop_2.setText(_translate("Form", "stop"))
        self.label_24.setText(_translate("Form", "Vision:"))
        self.label_25.setText(_translate("Form", "False"))
        self.label_7.setText(_translate("Form", "X position [m]:"))
        self.le_calibration_x.setText(_translate("Form", "0.0"))
        self.label_8.setText(_translate("Form", "Y position [m]:"))
        self.le_calibration_y.setText(_translate("Form", "0.0"))
        self.btn_cal_send_position.setText(_translate("Form", "Send position"))
        self.label_9.setText(_translate("Form", "Marker size [m]:"))
        self.le_marker_size.setText(_translate("Form", "0.9"))
        self.btn_cal_send_markersize.setText(_translate("Form", "Send marker size"))
        self.checkBox.setText(_translate("Form", "Autosend"))
        self.tb_sensors_submenu.setTabText(self.tb_sensors_submenu.indexOf(self.tb_sensors_calib), _translate("Form", "Calibration"))
        self.groupBox_17.setTitle(_translate("Form", "Deep settings"))
        self.label_2.setText(_translate("Form", "verbose:"))
        self.cb_verbose_active.setText(_translate("Form", "Activate"))
        self.label_17.setText(_translate("Form", "intrinsic_file:"))
        self.le_intrinsic_file.setText(_translate("Form", "23"))
        self.label_19.setText(_translate("Form", "cam_id:"))
        self.label_27.setText(_translate("Form", "cam_res:"))
        self.label_26.setText(_translate("Form", "framerate:"))
        self.label_29.setText(_translate("Form", "flip:"))
        self.cb_flip_cam.setText(_translate("Form", "Activate"))
        self.label_30.setText(_translate("Form", "broker:"))
        self.label_28.setText(_translate("Form", "database:"))
        self.label_31.setText(_translate("Form", "undistort:"))
        self.cb_undistort.setText(_translate("Form", "Activate"))
        self.label_32.setText(_translate("Form", "mask:"))
        self.cb_mask.setText(_translate("Form", "Activate"))
        self.label_33.setText(_translate("Form", "mask_file:"))
        self.tb_sensors_submenu.setTabText(self.tb_sensors_submenu.indexOf(self.tab), _translate("Form", "Settings"))
        self.groupBox_5.setTitle(_translate("Form", "Select sensor:"))
        self.lb_ip_text.setText(_translate("Form", "IP:"))
        self.lb_mode_text.setText(_translate("Form", "Status:"))
        self.groupBox_6.setTitle(_translate("Form", "Image view:"))
        self.label_18.setText(_translate("Form", "WARNING: This is going to stop the current process on the sensor. "))
        self.pushButton.setText(_translate("Form", "Load image"))
        self.tb_main.setTabText(self.tb_main.indexOf(self.tb_sensors), _translate("Form", "Sensors"))
        self.tb_main.setTabText(self.tb_main.indexOf(self.tb_vehicles), _translate("Form", "Vehicles"))
        self.pushButton_5.setText(_translate("Form", "Save log"))
        self.groupBox_3.setTitle(_translate("Form", "Loginfo"))
        self.label_6.setText(_translate("Form", "Selcet topic:"))
        self.pb_system_select_file.setText(_translate("Form", "Select File"))
        self.pb_record_start.setText(_translate("Form", "Start"))
        self.pb_record_stop.setText(_translate("Form", "Stop"))
        self.tb_main.setTabText(self.tb_main.indexOf(self.tb_system), _translate("Form", "System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
